name: 'Linear'
description: 'Integration with Linear app'
inputs:
  linear_access_token:
    description: 'developers.linear.app api access token'
    required: true
    default: ''
  GITHUB_TOKEN:
    description: 'Github api token'
    required: true
    default: ''
  package_json_path:
    description: 'List of package.json file path'
    required: true
    default: >-
outputs:
  time:
    description: 'Name output'
runs:
  using: 'node12'
  main: 'dist/index.js'
