on: [push]

jobs:
  insert_issue_labels:
    runs-on: ubuntu-latest
    name: Add labels to issues in Linear
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add labels to issues in Linear
        id: labels
        uses: ./
        with:
          linear_access_token: ${{ secrets.LINEAR_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
