on: [push, pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Create tags in linear.app
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print commit messages
        id: hello
        uses: ./
        with:
          linear_access_token: ${{ secrets.LINEAR_ACCESS_TOKEN }}
          labels: >-
            [{
              "branch": "develop",
              "label": "deployed-in-develop",
              "id": "52d57d00-d529-11eb-b8bc-0242ac130003"
            }, {
              "branch": "uat",
              "label": "deployed-in-uat",
              "id": "52d57d00-d529-11eb-b8bc-0242ac130003"
            }, {
              "branch": "staging",
              "label": "deployed-in-staging",
              "id": "b009aa6a-637d-4724-b98f-965d87e2d387"
            }, {
              "branch": "staging",
              "label": "deployed-in-staging",
              "id": "41f2cc70-e5cc-4a16-ba0d-891ef633d05a"
            }]
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
