on: [push]

jobs:
  insert_issue_labels:
    runs-on: ubuntu-latest
    name: Add labels to issues in Linear
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add labels to issues in Linear
        id: labels
        uses: ./
        with:
          linear_access_token: ${{ secrets.LINEAR_ACCESS_TOKEN }}
<<<<<<< HEAD
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
=======
          labels: >-
            [{
              "branch": "develop",
              "label": "deployed-in-develop",
              "id": "52d57d00-d529-11eb-b8bc-0242ac130003"
            }, {
              "branch": "uat",
              "label": "deployed-in-uat",
              "id": "52d57d00-d529-11eb-b8bc-0242ac130003"
            }, {
              "branch": "staging",
              "label": "deployed-in-staging",
              "id": "b009aa6a-637d-4724-b98f-965d87e2d387"
            }, {
              "branch": "staging",
              "label": "deployed-in-staging",
              "id": "41f2cc70-e5cc-4a16-ba0d-891ef633d05a"
            }]
>>>>>>> 71129cd (typescript version)
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
